// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXLXJJltaUdP3-YknUYqv_E0T90XT1dgE',
    appId: '1:512010707139:web:3434c2bfd20e8847adc276',
    messagingSenderId: '512010707139',
    projectId: 'ffive-1de0d',
    authDomain: 'ffive-1de0d.firebaseapp.com',
    storageBucket: 'ffive-1de0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw3UTt0MK1g_xbWZ_P4iruMjVy6_RZwPA',
    appId: '1:512010707139:android:f06310aa67063a39adc276',
    messagingSenderId: '512010707139',
    projectId: 'ffive-1de0d',
    storageBucket: 'ffive-1de0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7lD6qjNrCHNpydHN0ZoxYxv2LsW8igZg',
    appId: '1:512010707139:ios:5deadbb8fb5c7328adc276',
    messagingSenderId: '512010707139',
    projectId: 'ffive-1de0d',
    storageBucket: 'ffive-1de0d.appspot.com',
    iosBundleId: 'com.example.liveFfss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7lD6qjNrCHNpydHN0ZoxYxv2LsW8igZg',
    appId: '1:512010707139:ios:5deadbb8fb5c7328adc276',
    messagingSenderId: '512010707139',
    projectId: 'ffive-1de0d',
    storageBucket: 'ffive-1de0d.appspot.com',
    iosBundleId: 'com.example.liveFfss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXLXJJltaUdP3-YknUYqv_E0T90XT1dgE',
    appId: '1:512010707139:web:42af21d77984fd08adc276',
    messagingSenderId: '512010707139',
    projectId: 'ffive-1de0d',
    authDomain: 'ffive-1de0d.firebaseapp.com',
    storageBucket: 'ffive-1de0d.appspot.com',
  );
}
